Using Theano backend.
Using Theano backend.
Using Theano backend.
[2020-08-28 14:51:25,457 INFO] Loading data from data/814_train.h5
[2020-08-28 14:51:25,543 INFO] Loading data from data/812_train.h5
[2020-08-28 14:51:26,203 INFO] Loading data from data/824_train.h5
Using Theano backend.
[2020-08-28 14:51:29,451 INFO] Loading data from data/naturalsplittrainingsample.h5
[2020-08-28 14:51:38,538 INFO] Building model from share/reference_number.py
[2020-08-28 14:51:38,671 INFO] Building model from share/reference_number.py
Traceback (most recent call last):
  File "scripts/run_training.py", line 144, in <module>
    _main()
  File "scripts/run_training.py", line 99, in _main
    model, compile_args, fit_args, params = _build_model(path, data_x, data_y)
  File "scripts/run_training.py", line 66, in _build_model
    return buildf(data_x, data_y)
  File "share/reference_number.py", line 18, in build_model
    loss_function='categorical_crossentropy'
  File "python/keras_utils.py", line 48, in simple_model
    )(model)
  File "/global/homes/c/chkoda/miniconda2/envs/py2theano/lib/python2.7/site-packages/keras/engine/topology.py", line 583, in __call__
    input_shapes.append(K.int_shape(x_elem))
  File "/global/homes/c/chkoda/miniconda2/envs/py2theano/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 280, in int_shape
    raise TypeError('Not a Keras tensor:', x)
TypeError: ('Not a Keras tensor:', sigmoid.0)
srun: error: cgpu04: task 0: Exited with exit code 1
srun: Terminating job step 977600.0
[2020-08-28 14:51:46,388 INFO] Building model from share/reference_number.py
[2020-08-28 14:51:50,221 INFO] Building model from share/reference_number.py
Traceback (most recent call last):
  File "scripts/run_training.py", line 144, in <module>
    _main()
  File "scripts/run_training.py", line 99, in _main
    model, compile_args, fit_args, params = _build_model(path, data_x, data_y)
  File "scripts/run_training.py", line 66, in _build_model
    return buildf(data_x, data_y)
  File "share/reference_number.py", line 18, in build_model
    loss_function='categorical_crossentropy'
  File "python/keras_utils.py", line 48, in simple_model
    )(model)
  File "/global/homes/c/chkoda/miniconda2/envs/py2theano/lib/python2.7/site-packages/keras/engine/topology.py", line 583, in __call__
    input_shapes.append(K.int_shape(x_elem))
  File "/global/homes/c/chkoda/miniconda2/envs/py2theano/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 280, in int_shape
    raise TypeError('Not a Keras tensor:', x)
TypeError: ('Not a Keras tensor:', sigmoid.0)
srun: error: cgpu09: task 0: Exited with exit code 1
srun: Terminating job step 977600.2
Traceback (most recent call last):
  File "scripts/run_training.py", line 144, in <module>
    _main()
  File "scripts/run_training.py", line 99, in _main
    model, compile_args, fit_args, params = _build_model(path, data_x, data_y)
  File "scripts/run_training.py", line 66, in _build_model
    return buildf(data_x, data_y)
  File "share/reference_number.py", line 18, in build_model
    loss_function='categorical_crossentropy'
  File "python/keras_utils.py", line 48, in simple_model
    )(model)
  File "/global/homes/c/chkoda/miniconda2/envs/py2theano/lib/python2.7/site-packages/keras/engine/topology.py", line 583, in __call__
    input_shapes.append(K.int_shape(x_elem))
  File "/global/homes/c/chkoda/miniconda2/envs/py2theano/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 280, in int_shape
    raise TypeError('Not a Keras tensor:', x)
TypeError: ('Not a Keras tensor:', sigmoid.0)
srun: error: cgpu06: task 0: Exited with exit code 1
srun: Terminating job step 977600.1
Traceback (most recent call last):
  File "scripts/run_training.py", line 144, in <module>
    _main()
  File "scripts/run_training.py", line 99, in _main
    model, compile_args, fit_args, params = _build_model(path, data_x, data_y)
  File "scripts/run_training.py", line 66, in _build_model
    return buildf(data_x, data_y)
  File "share/reference_number.py", line 18, in build_model
    loss_function='categorical_crossentropy'
  File "python/keras_utils.py", line 48, in simple_model
    )(model)
  File "/global/homes/c/chkoda/miniconda2/envs/py2theano/lib/python2.7/site-packages/keras/engine/topology.py", line 583, in __call__
    input_shapes.append(K.int_shape(x_elem))
  File "/global/homes/c/chkoda/miniconda2/envs/py2theano/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 280, in int_shape
    raise TypeError('Not a Keras tensor:', x)
TypeError: ('Not a Keras tensor:', sigmoid.0)
srun: error: cgpu18: task 0: Exited with exit code 1
srun: Terminating job step 977600.3
